project:
  type: website
  output-dir: docs
  resources:
    - "/pages/download/_download.json"
    - "/pages/download/_prerelease.json"
    - "/_redirects"

website:
  title: "LANAL/UFG"
  image: "quarto-dark-bg.jpeg"
  favicon: "favicon.png"
  open-graph: true
  twitter-card: false
  site-url: "https://lanal-ufg.github.io/lanal-ufg"
  repo-url: https://github.com/lanal-ufg/lanal-ufg
  issue-url: https://github.com/lanal-ufg/lanal-ufg/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  search:
    type: overlay
    algolia:
      index-name: prod_QUARTO
      application-id: ZPJB5I1QN7
      search-only-api-key: 41be6c1e0a7fea4a51b107810facf577
      analytics-events: true
      show-logo: true
  page-footer:
    # left: |
      # Este é um laboratório da UFG
    center:
      - text: "Sobre"
        href: about.qmd
      - text: "Perguntas frequentes"
        href: pages/faq/index.qmd
      # - text: "Licença"
        # href: license.qmd
      - text: "Acesso à informação"
        href: informação.qmd
    # right:
      # - icon: instagram
        # href: https://www.instagram.com/lanal.ufg
        # aria-label: Instagram LANAL
      # - icon: github
        # href: https://github.com/lanal-ufg/lanal-ufg
        # aria-label: GitHub LANAL
      # - icon: rss
        # href: https://lanal-ufg.github.io/lanal-ufg/docs/pages/blog/index.xml
        # aria-label: Feed RSS do Blog do LANAL        
  navbar:
    background: light
    logo: logo_LANAL.png
    logo-alt: "Logo LANAL"
    title: false
    collapse-below: lg
    left:
      - text: "Apresentação"
        href: index.qmd
      - text: "Cadastro"
        href: pages/cadastro/index.qmd
      - text: "Procedimentos"
        href: pages/procedimentos/index.qmd
      - text: Atividades
        href: pages/atividades/index.qmd
      - text: "Publicações"
        href: pages/publicações/index.qmd
      - text: "Galeria"
        href: docs/gallery/index.qmd
      - text: "Blog"
        href: pages/blog/index.qmd
      - text: "Ajuda"
        menu:
          - text: "Perguntas frequentes"
            icon: "question-circle"
            href: pages/faq/index.qmd
          - text: "Envie-nos um e-mail"
            icon: "Envelope"
            href: "mailto://lanal.fanut@ufg.br"
          ## - text: "Informe um incidente"
            ## icon: "bug"
            ## href: "https://github.com/lanal-ufg/lanal-ufg/issues"
          ## - text: "Faça uma pergunta"
            ## icon: "chat-right-text"
            ## href: https://github.com/lanal-ufg/lanal-ufg/discussions"
    tools:
      - icon: instagram
        href: https://www.instagram.com/lanal.ufg
        text: Instagram LANAL
      # - icon: github
        # href: https://github.com/lanal-ufg/lanal-ufg
        # text: GitHub do LANAL
      # - icon: rss
        # href: https://lanal-ufg.github.io/lanal-ufg/docs/pages/blog/index.xml
        # text: RSS Blog do LANAL        

  sidebar:
    - id: apresentação
      title: "Apresentação"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - text: "Apresentação"
          href: index.qmd
        - text: "Infraestrutura"
          href: pages/apresentação/infraestrutura/
        - text: "Segurança"
          href: pages/apresentação/segurança/
        - text: "Normas"  
          href: pages/apresentação/normas/
        - text: "Agenda"
          href: pages/apresentação/agenda/

    - id: procedimentos
      collapse-level: 1
      contents:
        - section: "Procedimentos"
          href: pages/procedimentos/index.qmd
          contents:
          - section: "Analíticos"
            contents:
              - section: "Composição centesimal"
                contents:
                  - pages/procedimentos/analíticos/PAN 001 - Umidade a 105C.qmd
                  - pages/procedimentos/analíticos/PAN 002 - Resíduo mineral fixo.qmd
                  - pages/procedimentos/analíticos/PAN 003 - Lipídeos por Soxhlet.qmd
                  - pages/procedimentos/analíticos/PAN 004 - Lipídeos por Bligh e Dyer.qmd
                  - pages/procedimentos/analíticos/PAN 005 - Proteínas totais.qmd
              - section: "Capacidade antioxidante"
                contents:
                  - pages/procedimentos/analíticos/PAN 006 - Capacidade antioxidante por DPPH.qmd
                  - pages/procedimentos/analíticos/PAN 007 - Capacidade antioxidante por FRAP.qmd
                  - pages/procedimentos/analíticos/PAN 008 - Capacidade antioxidante por ABTS.qmd
              - section: "Compostos bioativos"
                contents:
                  - pages/procedimentos/analíticos/PAN 009 - Compostos fenólicos totais.qmd
                  - pages/procedimentos/analíticos/PAN 010 - Flavonoides totais.qmd
                  - pages/procedimentos/analíticos/PAN 011 - Carotenoides totais.qmd
          - section: "Operacionais"
            contents:
              - docs/computations/python.qmd
              - docs/computations/r.qmd
              - docs/computations/julia.qmd
              - docs/computations/ojs.qmd
              - docs/computations/execution-options.qmd
              - docs/computations/parameters.qmd
          - section: "Administrativos"
            contents:
              - section: "JupyterLab"
                contents:
                  - text: "JupyterLab Basics"
                    href: docs/tools/jupyter-lab.qmd
                  - text: "JupyterLab Extension"
                    href: docs/tools/jupyter-lab-extension.qmd
              - section: "RStudio IDE"
                contents: 
                  - text: "RStudio Basics"
                    href: docs/tools/rstudio.qmd
                  - section: "Visual Editor"
                    href: docs/visual-editor/index.qmd
                    contents:
                      - text: Editor Basics
                        href: docs/visual-editor/index.qmd
                      - docs/visual-editor/technical.qmd
                      - docs/visual-editor/content.qmd
                      - docs/visual-editor/options.qmd
                      - docs/visual-editor/markdown.qmd
              - section: "VS Code"
                href: docs/tools/vscode.qmd
                contents:
                  - text: "VS Code Basics"
                    href: docs/tools/vscode.qmd
                  - text: "Visual Editor"
                    href: docs/visual-editor/vscode/index.qmd
                  - text: "Notebook Editor"
                    href: docs/tools/vscode-notebook.qmd
                
              - docs/tools/neovim.qmd
              - docs/tools/text-editors.qmd
    - id: atividades
      title: "Atividades"
      contents:
        - "---"
        - section: pages/atividades/index.qmd
          contents: 
            - text: "Ensino"
              href: pages/atividades/listing-filters.qmd
            - text: "Pesquisa"
              href: pages/atividades/listing-journals.qmd
            - text: "Extensão"
              href: pages/atividades/listing-formats.qmd
            - text: "Gestão"
        - "---"
        - section: pages/atividades/creating.qmd
          contents:
            - text: "Overview"
              href: pages/extensions/creating.qmd
            - docs/extensions/lua.qmd
            - docs/extensions/lua-api.qmd
            - text: "Distribution"
              href: docs/extensions/distributing.qmd
            - "---"
            - text: "Shortcodes"
              href: docs/extensions/shortcodes.qmd
            - text: "Filters"
              href: docs/extensions/filters.qmd
            - section: "Journal Articles"
              href: docs/journals/formats.qmd
              contents:
                - docs/journals/formats.qmd
                - docs/journals/templates.qmd
                - docs/journals/authors.qmd
            - docs/extensions/formats.qmd
            - docs/extensions/revealjs.qmd
            - docs/extensions/project-types.qmd
            - docs/extensions/starter-templates.qmd
    - id: manuscripts
      title: "Manuscripts"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - text: Manuscripts Overview
          href: docs/manuscripts/index.qmd
        - text: "Authoring Manuscripts"
          contents: 
            - text: Jupyter Lab
              href: docs/manuscripts/authoring/jupyterlab.qmd
            - text: VS Code
              href: docs/manuscripts/authoring/vscode.qmd
            - text: RStudio
              href: docs/manuscripts/authoring/rstudio.qmd
        - text: "Publishing Manuscripts"
          href: docs/manuscripts/publishing.qmd
        - text: "Next Steps"
          href: docs/manuscripts/next-steps.qmd
        - text: "---"
        - text: "Manuscript Components"
          href: docs/manuscripts/components.qmd
          
        
    - id: publicações
      title: "Publicações"
      collapse-level: 3
      contents:
        - section: "Publicações"
          href: pages/publicações/index.qmd
          contents:
          - section: "Artigos"
            contents:
              - text: "HTML"
                href: docs/reference/formats/html.qmd
              - text: "PDF"
                href: docs/reference/formats/pdf.qmd
              - text: "MS Word"
                href: docs/reference/formats/docx.qmd
              - text: "OpenOffice"
                href: docs/reference/formats/odt.qmd
              - text: "ePub"
                href: docs/reference/formats/epub.qmd
              - section: "Presentations"
                contents:
                  - text: "Revealjs"
                    href: docs/reference/formats/presentations/revealjs.qmd
                  - text: "PowerPoint"
                    href: docs/reference/formats/presentations/pptx.qmd
                  - text: "Beamer"
                    href: docs/reference/formats/presentations/beamer.qmd
              - section: "Markdown"
                contents:
                  - text: "GitHub"
                    href: docs/reference/formats/markdown/gfm.qmd
                  - text: "CommonMark"
                    href: docs/reference/formats/markdown/commonmark.qmd
                  - text: "Markua"
                    href: docs/reference/formats/markdown/markua.qmd
              - section: "Wikis"
                contents:
                  - text: "MediaWiki"
                    href: docs/reference/formats/wiki/mediawiki.qmd
                  - text: "DokuWiki"
                    href: docs/reference/formats/wiki/dokuwiki.qmd
                  - text: "ZimWiki"
                    href: docs/reference/formats/wiki/zimwiki.qmd
                  - text: "Jira Wiki"
                    href: docs/reference/formats/wiki/jira.qmd
                  - text: "XWiki"
                    href: docs/reference/formats/wiki/xwiki.qmd
              - section: "More Formats"
                contents:
                  - text: "JATS"
                    href: docs/reference/formats/jats.qmd
                  - text: "Jupyter"
                    href: docs/reference/formats/ipynb.qmd
                  - text: "ConTeXt"
                    href: docs/reference/formats/context.qmd
                  - text: "RTF"
                    href: docs/reference/formats/rtf.qmd
                  - text: "reST"
                    href: docs/reference/formats/rst.qmd
                  - text: "AsciiDoc"
                    href: docs/reference/formats/asciidoc.qmd
                  - text: "Org-Mode"
                    href: docs/reference/formats/org.qmd
                  - text: "Muse"
                    href: docs/reference/formats/muse.qmd
                  - text: "GNU TexInfo"
                    href: docs/reference/formats/texinfo.qmd
                  - text: "Groff Man Page"
                    href: docs/reference/formats/man.qmd
                  - text: "Groff Manuscript"
                    href: docs/reference/formats/ms.qmd
                  - text: "Haddock markup"
                    href: docs/reference/formats/haddock.qmd
                  - text: "OPML"
                    href: docs/reference/formats/opml.qmd
                  - text: "Textile"
                    href: docs/reference/formats/textile.qmd
                  - text: "DocBook"
                    href: docs/reference/formats/docbook.qmd
                  - text: "InDesign"
                    href: docs/reference/formats/icml.qmd
                  - text: "TEI Simple"
                    href: docs/reference/formats/tei.qmd
                  - text: "FictionBook"
                    href: docs/reference/formats/fb2.qmd
          - section: "Teses e Dissertações"
            contents:
              - text: "Jupyter"
                href: docs/reference/cells/cells-jupyter.qmd
              - text: "Knitr"
                href: docs/reference/cells/cells-knitr.qmd
              - text: "Observable"
                href: docs/reference/cells/cells-ojs.qmd
          - section: "Trabalhos de Conclusão de curso"
            contents:
              - text: "Options"
                href: docs/reference/projects/options.qmd
              - text: "Websites"
                href: docs/reference/projects/websites.qmd
              - text: "Books"
                href: docs/reference/projects/books.qmd
          - section: "Outras"
            contents:
              - text: "Dates"
                href: docs/reference/dates.qmd
              - text: "Globs"
                href: docs/reference/globs.qmd
              - text: "Citations"
                href: docs/reference/metadata/citation.qmd
    - id: prerelease
      title: "Quarto 1.3"
      contents:
        - section: "Highlights"
          href: docs/prerelease/1.3/index.qmd
          contents:
            - text: "Confluence Publishing"
              href: docs/publishing/confluence.qmd
            - text: "Multi-Format"
              href: docs/output-formats/html-multi-format.qmd
            - text: "Cell Embedding"
              href: docs/authoring/notebook-embed.qmd
            - text: "Grid Customization"
              href: docs/output-formats/page-layout.qmd#grid-customization
            - text: "Code Annotation"
              href: docs/authoring/code-annotation.qmd
            - section: "Quarto AST"
              href: docs/prerelease/1.3/ast.qmd
              contents:
                - text: Callouts
                  href: docs/prerelease/1.3/custom-ast-nodes/callout.qmd
                - text: Tabsets
                  href: docs/prerelease/1.3/custom-ast-nodes/tabset.qmd
                - text: Conditional Blocks
                  href: docs/prerelease/1.3/custom-ast-nodes/conditional-block.qmd
            - text: "Mermaid Theming"
              href: docs/authoring/diagrams.qmd#mermaid-theming
            - text: "PDF Images"
              href: docs/prerelease/1.3/pdf.qmd
            - text: "`kbd` Shortcode"
              href: docs/authoring/markdown-basics.qmd#keyboard-shortcuts

 

bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px


filters:
  - filters/tools-tabset.lua


freeze: true

editor: visual

profile:
  group: 
    - [prerelease,rc]