project:
  type: website
  output-dir: docs
# resources:
  # - "/pages/download/_download.json"
  # - "/pages/download/_prerelease.json"
  # - "/_redirects"

website:
  title: "LANAL/UFG"
  image: "quarto-dark-bg.jpeg"
  favicon: "favicon.png"
  open-graph: true
  twitter-card: false
  site-url: "https://lanal-ufg.github.io/lanal-ufg"
# repo-url: https://github.com/lanal-ufg/lanal-ufg
# issue-url: https://github.com/lanal-ufg/lanal-ufg/issues/new/choose
# repo-actions: [edit, issue]
# reader-mode: true
  page-navigation: true
  search:
    type: overlay
    algolia:
      index-name: dev_lanalufg
      application-id: FTGUXGZRDK
      search-only-api-key: 082d80d81a39d75f3bdffe8acf2338fa
      analytics-events: true
      show-logo: true
  page-footer:
  # left: |
    # Este é um laboratório da UFG
    center:
      - text: "Sobre"
        href: about.qmd
      - text: "Perguntas frequentes"
        href: pages/faq/index.qmd
    # - text: "Licença"
      # href: license.qmd
      - text: "Acesso à informação"
        href: informação.qmd
  # right:
    # - icon: instagram
      # href: https://www.instagram.com/lanal.ufg
      # aria-label: Instagram LANAL
    # - icon: github
      # href: https://github.com/lanal-ufg/lanal-ufg
      # aria-label: GitHub LANAL
    # - icon: rss
      # href: https://lanal-ufg.github.io/lanal-ufg/docs/pages/blog/index.xml
      # aria-label: Feed RSS do Blog do LANAL        
  navbar:
    background: light
    logo: logo_LANAL.png
    logo-alt: "Logo LANAL"
    title: false
    collapse-below: lg
    left:
      - text: "LANAL/UFG"
        href: index.qmd
      - text: "Segurança"
        href: pages/seguranca/index.qmd
      - text: "Cadastro"
        href: pages/cadastro/novos.qmd
      - text: "Procedimentos"
        href: pages/procedimentos/index.qmd
    # - text: Atividades
      # href: pages/atividades/index.qmd
      - text: "Agenda"
        href: pages/agenda/index.qmd
      - text: "Publicações"
        href: pages/publicações/index.qmd
      - text: "Blog"
        href: pages/blog/index.qmd
      - text: "Ajuda"
        menu:
          - text: "Perguntas frequentes"
            icon: "question-circle"
            href: pages/faq/index.qmd
          - text: "Envie-nos um e-mail"
            icon: "Envelope"
            href: "mailto://lanal.fanut@ufg.br"
       ## - text: "Informe um incidente"
         ## icon: "bug"
         ## href: "https://github.com/lanal-ufg/lanal-ufg/issues"
       ## - text: "Faça uma pergunta"
         ## icon: "chat-right-text"
         ## href: https://github.com/lanal-ufg/lanal-ufg/discussions"
    tools:
      - icon: instagram
        href: https://www.instagram.com/lanal.ufg
        text: Instagram LANAL
    # - icon: github
      # href: https://github.com/lanal-ufg/lanal-ufg
      # text: GitHub do LANAL
    # - icon: rss
      # href: https://lanal-ufg.github.io/lanal-ufg/docs/pages/blog/index.xml
      # text: RSS Blog do LANAL        

  sidebar:
    - id: apresentação
      title: "Apresentação"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - text: "Apresentação"
          href: index.qmd
        - text: "Equipe"
          href: equipe.qmd
        - section: "Infraestrutura"  
          contents:
            - text: "Instalações"
              href: pages/apresentação/infraestrutura/instalacoes.qmd
            - text: "Equipamentos"
              href: pages/apresentação/infraestrutura/equipamentos.qmd
            - text: "Reagentes"
              href: pages/apresentação/infraestrutura/reagentes.qmd
        - text: "Normas"  
          href: pages/apresentação/normas/index.qmd
    
    - id: seguranca
      title: "Segurança"
      style: "floating"
      collapse-level: 3
      alignment: left
      contents:
        - section: "Segurança no LANAL/UFG"
          href: pages/seguranca/index.qmd
          contents:
          - text: "Diretrizes de segurança"
            href: pages/seguranca/diretrizes/index.qmd
          - text: "Mapa de riscos"
            href: pages/seguranca/mapa de riscos/index.qmd
          - text: "Fichas de segurança (FDS)"
            href: pages/seguranca/fds/index.qmd

    - id: cadastro
      title: "Cadastro"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - text: "Novos alunos"
          href: pages/cadastro/novos.qmd
        - text: "Atualização de cadastro"
          href: pages/cadastro/atualiza.qmd

    - id: procedimentos
      collapse-level: 1
      contents:
        - section: "Procedimentos"
          href: pages/procedimentos/index.qmd
          contents:
          - text: "Métodos Analíticos"
            href: pages/procedimentos/analiticos/index.qmd
          - text: "Operação de equipamentos"
            href: pages/procedimentos/operacionais/peq/index.qmd
          - text: "Preparo de soluções"
            href: pages/procedimentos/operacionais/pps/index.qmd
          - text: "Disposição de resíduos"
            href: pages/procedimentos/operacionais/pdr/index.qmd
        # - section: "Administrativos"
          # contents:
            # - section: "Pesquisa"
              # contents:
                # - pages/procedimentos/administrativos/PAP 001.md
            # - section: "Ensino"
              # contents: 
                # - pages/procedimentos/administrativos/PAE 001.md
            # - section: "Extensão"
              # contents:
                # - pages/procedimentos/administrativos/PAX 001.md

  # - id: atividades
    # title: "Atividades"
    # contents:
      # - section: pages/atividades/index.qmd
        # contents: 
          # - text: "Ensino"
            # href: pages/atividades/listing-filters.qmd
          # - text: "Pesquisa"
            # href: pages/atividades/listing-journals.qmd
          # - text: "Extensão"
            # href: pages/atividades/listing-formats.qmd
          # - text: "Gestão"
      
bibliography: pages/publicações/bibliografia-lanal.json

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 350px


filters:
  - filters/tools-tabset.lua


freeze: true

editor: visual

profile:
  group: 
    - [prerelease,rc]